[package]
name = "artichoke-backend"
version = "0.6.0"
authors = ["Ryan Lopopolo <rjl@hyperbo.la>"]
edition = "2021"
rust-version = "1.58.1"
description = "Embeddable VM implementation for Artichoke Ruby"
repository = "https://github.com/artichoke/artichoke"
readme = "README.md"
license = "MIT"
keywords = ["artichoke", "artichoke-ruby", "mruby", "ruby"]
categories = ["api-bindings"]

[dependencies]
artichoke-core = { version = "0.10.0", path = "../artichoke-core" }
artichoke-load-path = { version = "0.1.0", path = "../artichoke-load-path", default-features = false }
bstr = { version = "0.2.9", default-features = false, features = ["std"] }
cstr = "0.2.4"
intaglio = "1.4.0"
onig = { version = "6.3.0", optional = true, default-features = false }
regex = "1"
scolapasta-string-escape = { version = "0.2.0", path = "../scolapasta-string-escape", default-features = false }
spinoso-array = { version = "0.7.0", path = "../spinoso-array", default-features = false }
spinoso-env = { version = "0.1.1", path = "../spinoso-env", optional = true, default-features = false }
spinoso-exception = { version = "0.1.0", path = "../spinoso-exception" }
spinoso-math = { version = "0.2.0", path = "../spinoso-math", optional = true, default-features = false }
spinoso-random = { version = "0.2.0", path = "../spinoso-random", optional = true }
spinoso-regexp = { version = "0.2.0", path = "../spinoso-regexp", optional = true, default-features = false }
spinoso-securerandom = { version = "0.1.0", path = "../spinoso-securerandom", optional = true }
spinoso-string = { version = "0.11.0", path = "../spinoso-string" }
spinoso-symbol = { version = "0.1.0", path = "../spinoso-symbol" }
spinoso-time = { version = "0.2.0", path = "../spinoso-time", optional = true }

[dev-dependencies]
quickcheck = { version = "1.0.3", default-features = false }

[build-dependencies]
cc = "1.0.73"
target-lexicon = "0.12.3"

[features]
default = [
  "core-full",
  "stdlib-full",
]

core-full = [
  "core-env",
  "core-env-system",
  "core-math",
  "core-math-full",
  "core-random",
  "core-regexp-oniguruma",
  "core-time",
]
core-env = ["spinoso-env"]
core-env-system = ["core-env", "spinoso-env/system-env"]
core-math = ["spinoso-math"]
core-math-full = ["core-math", "spinoso-math/full"]
core-random = ["spinoso-random"]
core-regexp = ["spinoso-regexp"]
core-regexp-oniguruma = ["core-regexp", "spinoso-regexp/oniguruma", "onig"]
core-time = ["spinoso-time"]

load-path-native-file-system-loader = ["artichoke-load-path/native-file-system-loader"]
load-path-rubylib-native-file-system-loader = ["load-path-native-file-system-loader", "artichoke-load-path/rubylib-native-file-system-loader"]

output-strategy-capture = []
output-strategy-null = ["output-strategy-capture"]

stdlib-full = [
  "stdlib-abbrev",
  "stdlib-base64",
  "stdlib-cmath",
  "stdlib-delegate",
  "stdlib-forwardable",
  "stdlib-json",
  "stdlib-monitor",
  "stdlib-ostruct",
  "stdlib-securerandom",
  "stdlib-set",
  "stdlib-shellwords",
  "stdlib-strscan",
  "stdlib-time",
  "stdlib-uri",
]
stdlib-abbrev = []
stdlib-base64 = []
stdlib-cmath = ["core-math"]
stdlib-delegate = []
stdlib-forwardable = []
stdlib-json = []
stdlib-monitor = []
stdlib-ostruct = []
stdlib-securerandom = ["spinoso-securerandom"]
stdlib-set = []
stdlib-shellwords = []
stdlib-strscan = []
stdlib-time = []
stdlib-uri = []

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
